openapi: 3.0.3
info:
  title: ''
  version: 1.0.0
paths:
  /legislation/types:
    get:
      summary: get available document types
      parameters:
        - name: indent
          in: query
          required: false
          schema:
            type: string
            enum:
              - 'true'
              - 'false'
      responses:
        '200':
          description: the types
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      description: the document type (e.g. UnitedKingdomPublicGeneralAct, ScottishStatutoryInstrument)
                      type: string
                    acronym:
                      description: the abbreviation (or initialism) used to refer to entities belonging to a class (e.g. ukpga, ssi, nisi).
                      type: string
                    label:
                      description: a human-readable version of the type's name
                      type: string
                    class:
                      description: the class of legislation to which the type belongs
                      type: string
                      enum:
                        - Primary
                        - Secondary
                        - EuropeanUnionLegislation
                    comment:
                      description: a human-readable description of the type
                      type: string
        '400':
          description: bad request
        '500':
          description: internal error
  /legislation/years/{type}:
    get:
      summary: get available years for a document type
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
        - name: indent
          in: query
          required: false
          schema:
            type: string
            enum:
              - 'true'
              - 'false'
      responses:
        '200':
          description: the available years for a document type
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      description: the document type
                      type: string
                    acronym:
                      description: the abbreviation of the document type
                      type: string
                    year:
                      description: the year
                      type: integer
                    documents:
                      description: the number of documents of the type in the year
                      type: integer
        '400':
          description: bad request
        '500':
          description: internal error
  /legislation/documents/{type}/{year}:
    get:
      summary: get available documents for a document type and year
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
        - name: year
          in: path
          required: true
          schema:
            type: integer
        - name: indent
          in: query
          required: false
          schema:
            type: string
            enum:
              - 'true'
              - 'false'
      responses:
        '200':
          description: the available documents for a document type and year
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      description: the document type
                      type: string
                    acronym:
                      description: the abbreviation of the document type
                      type: string
                    year:
                      description: the year
                      type: integer
                    number:
                      description: the number of the document
                      type: integer
                    id:
                      description: the unique id of the document
                      type: string
                    title:
                      description: the title of the document
                      type: string
        '400':
          description: bad request
        '500':
          description: internal error
